name: Builds - PAL3A - Mono - iOS

on: [push, pull_request]

jobs:
  build_pal3a_mono_ios:
    name: Build PAL3A for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          lfs: true
      - name: Switch define symbol from PAL3 to PAL3A
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "PAL3"
          replace: "PAL3A"
          include: "**ProjectSettings.asset"
      - name: Replace PAL3 game icon with PAL3A one
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "6b32649dccc45df4ebe8e3f8eccee249"
          replace: "d03d417e5660d5849939c8fe43732dbd"
          include: "**ProjectSettings.asset"
      - uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: PAL3A
          versioning: Semantic
      # do not upload artifacts for iOS builds